name: wf-release-lbu
on:
  push:
    branches:
      - "release/*"
  workflow_dispatch: 
jobs:
  rel-lint-job:
    runs-on: ubuntu-latest
    steps:
      - name: chekcout repository
        uses: actions/checkout@v4
        with:
          ref: ${{github.ref}}
      - name: Checkedout Branch
        run: |
          echo "________________________"
          echo "${{github.ref}}"
          echo "________________________"
      - name: Lint HTML and Stylelint
        run: |
          npx htmlhint "**/*.html"
          npx stylelint "**/*.css"
      - name: Build With Parcel
        run: |
          npx parcel build "./src/index.html" --dist-dir "./rel" --public-url "./"
      - name: Upload Build Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          name: "release-artifact"
          path: "./rel"
  rel-dep-job:
    needs: rel-lint-job
    environment: staging
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploye In Staging
        run: echo "Going To Deploye In the Production Environment"
      - name: Upload To Staging Environment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: "release-artifact"
          token: ${{github.token}}
