name: wf-production-lbd
on:
  pull_request:
    branches:
      - prod 
  push:
    branches:
      - prod
  workflow_dispatch: 
jobs:
  prod-lint-job:
    runs-on: ubuntu-latest
    steps:
      - name: chekcout repository
        uses: actions/checkout@v4
        with:
          ref: ${{github.ref}}
      - name: Checked Out Branch???
        run: |
          echo "____________________"
          echo "${{github.ref}}"
          echo "____________________"
      - name: Lint HTML and Stylelint
        run: |
          npx htmlhint "**/*.html"
          npx stylelint "**/*.css"
      - name: Build With Parcel
        run: |
          npx parcel build "./src/index.html" --dist-dir "./prod" --public-url "./"
      - name: Upload Build Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          name: prod-artifact
          path: "./prod"
  prod-dep-job:
    needs: prod-lint-job
    environment: production
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Upload To Production Environment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: prod-artifact
          token: ${{github.token}}
